[workspace]
resolver = "3"
members = [
  "lsf",
  "cardinal-sdk",
  "fswalk",
  "namepool",
  "was",
  "fs-icon",
  "query-segmentation",
  "cardinal-syntax",
  "search-cancel",
]
exclude = ["cardinal"]
