[package]
name = "fswalk"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1.0"
rayon = "1"
memchr = "2.7.4"
enumn = "0.1.14"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
tempdir = "0.3"
