[package]
name = "namepool"
version = "0.1.0"
edition = "2024"

[dependencies]
memchr = "2"
rayon = "1"
serde = { version = "1", features = ["derive"] }
itertools = "0.14"
parking_lot = "0.12"
rustc-hash = "2.1.1"
regex = "1"
tracing = "0.1"
